### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by zylerdev** [chinoogawa/instaBrute#18]
only just found out about this, and im quite interested in it.

I installed in the modules etc.. however when I test the dictionary attack, it seems just to sit there idle not doing anything on the "Using 1 seconds of delay"

![image](https://cloud.githubusercontent.com/assets/16195172/17197426/8f56f3f8-5464-11e6-9385-3e14b5616fc4.png)

it sits here and i have waited for a while.
and if this project is dead, then can someone let me know, because then i'd like to make something similar to this. :)
ty.

**Comment by aleperno** [comment]
Hmm...I can thinkg of multiple answers to your questions.
What does a dead project mean?
If you mean that those who contributed to its code now aren't, well...at least we could say it's stalled. We are both currently under heavy load with labor and personal issues; though there are some new features and improvemets we want to add (and hopefully do so).

Regarding why the script idles, I should check, it's been a while since I last tested it (2 months perhaps).

For me, a projects is dead when no-one is using it or contributing to it. Being this project under the GPL license, you can freely fork it and make your own derivation. And why not make a pull request!?

Ps: Is your "Garbage" folder a homage to the "Hackers" movie? If it is, pretty cool :+1:

**Comment by zylerdev** [comment]
@aleperno thankyou for the response, and yes thats what I meant by a dead project.
I didn't know you guys were so busy and under heavy load so that explains the inactivity on this, once again thanks for taking a look at my post. I'm not very experienced with Python, however I might take a look at what I can do and see if I can get some cool features from this current build.

ps; I haven't seen the movie, and I literally just called my folder garbage for no reason :p
